### ISSUE TITLE
.DS_store

### ISSUE THREAD

**Issue by sunwoo0706** [yjnoh1016/TIL#1]
`.DS_store` 가 원격 저장소에 올려져 있는것 같습니다.
`.gitignore` 시키면 될 것 같네요 !!

[.gitignore 참고 자료](https://velog.io/@psk84/.gitignore-적용하기)

**Comment by siwony** [comment]
그리고 `.gitignore`해도 저장소에 안지워질 수 있습니다. 그럴경우 git 캐시삭제 참고해주세요!

[모든 .DS_store ignore 삭제하기 참고자료](https://github.com/siwony/TIL/blob/main/Git/ds-store-ignore.md)
[git 캐시삭제하기 참고자료](https://niceman.tistory.com/114)

**Comment by Goolgae** [comment]
.gitignore가 없는데 캐시 삭제를 왜 하죠?

**Comment by siwony** [comment]
간혹 ignore를해도 원격저장소에서는 삭제되지 않는 이슈가 자주 있어서 참고로 말씀드린겁니다.

**Comment by Goolgae** [comment]
간혹의 경우가 이미 `.gitignore`가 있어서 그런거잖아 근데 연주는 안 넣었어 시.원.아

**Comment by siwony** [comment]
간혹 그런경우가 있어서 comment남겼습니다. ^^

**Comment by noplayyy** [comment]
네! 조언 감사합니다. 말씀해 주신 내용을 토대로 수정하겠습니다 :)
